import image_loading from '../../../../image/giay_the_thao.jpg';
import my_image from '../../../../image/my_image.png';
import naruto_x_hinata from '../../../../image/naruto_x_hinata.jpg';

//
export const owner_info = [
    {
        title: 'Rating',
        value: 4.6,
    },
    {
        title: 'Reply chat',
        value: '100%',
    },
    {
        title: 'Time join',
        value: '2021-04-13T21:25:13.739874Z',
    },
    {
        title: 'Products',
        value: 400,
    },
    {
        title: 'Reply time',
        value: new Date().toLocaleString(),
    },
    {
        title: 'Follow',
        value: 600000,
    },
];

//
export const default_arr_shop = [
    {
        id: 2,
        list_name: [
            {
                name: 'baby',
                title: 'Baby',
            },
            {
                name: 'mom',
                title: 'Mom',
            },
            {
                name: 'other',
                title: 'Other',
            },
        ],
        vid_pics: [
            {
                id: 4,
                vid_pic: image_loading,
                shop_model: 2,
            },
            {
                id: 9,
                vid_pic: image_loading,
                shop_model: 2,
            },
            {
                id: 17,
                vid_pic: image_loading,
                shop_model: 2,
            },
            {
                id: 21,
                vid_pic: image_loading,
                shop_model: 2,
            },
        ],
        products: [
            {
                id: 4,
                vid_pics: [
                    {
                        id: 12,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 53,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 71,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 76,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 91,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 94,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 99,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                    {
                        id: 100,
                        vid_pic: image_loading,
                        product_model: 4,
                    },
                ],
                comments: [
                    {
                        id: 28,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '22',
                        created_time: '2021-04-18T07:21:04.632269Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 27,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '21',
                        created_time: '2021-04-18T07:21:02.066646Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 26,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '20',
                        created_time: '2021-04-18T07:21:00.775763Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 25,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '19',
                        created_time: '2021-04-18T07:20:55.118716Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 24,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '18',
                        created_time: '2021-04-18T07:20:52.392768Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 23,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '17',
                        created_time: '2021-04-18T07:20:48.955884Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 22,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '16',
                        created_time: '2021-04-18T07:20:47.465301Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 21,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'v',
                        created_time: '2021-04-18T07:20:39.728042Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 20,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'aa',
                        created_time: '2021-04-18T07:20:36.128428Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 19,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '13',
                        created_time: '2021-04-18T07:11:10.646666Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 18,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '12',
                        created_time: '2021-04-18T07:11:08.314178Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 17,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '11',
                        created_time: '2021-04-18T07:10:36.400212Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 16,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '10',
                        created_time: '2021-04-18T07:09:51.665759Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 15,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '9',
                        created_time: '2021-04-18T07:02:54.983982Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 14,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '8',
                        created_time: '2021-04-18T07:02:51.196627Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 11,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: '1 1',
                        created_time: '2021-04-18T02:03:37.827763Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 10,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'ad asda sda',
                        created_time: '2021-04-18T02:03:30.190410Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 9,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [
                            {
                                id: 2,
                                vid_pic: image_loading,
                                comment_model: 9,
                            },
                            {
                                id: 3,
                                vid_pic: image_loading,
                                comment_model: 9,
                            },
                            {
                                id: 4,
                                vid_pic: image_loading,
                                comment_model: 9,
                            },
                            {
                                id: 5,
                                vid_pic: image_loading,
                                comment_model: 9,
                            },
                        ],
                        count_vid_pic: 4,
                        text: '12 21 213 3',
                        created_time: '2021-04-18T02:03:22.308944Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 8,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [
                            {
                                id: 1,
                                vid_pic: image_loading,
                                comment_model: 8,
                            },
                        ],
                        count_vid_pic: 1,
                        text: '1 2 3',
                        created_time: '2021-04-18T02:02:51.284422Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 7,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'a sd a asd asd',
                        created_time: '2021-04-18T02:00:18.002912Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                    {
                        id: 6,
                        user: {
                            id: 1,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'Nguyen',
                            last_name: 'Dat',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'a a sda sa',
                        created_time: '2021-04-18T01:59:58.406636Z',
                        product_model: 4,
                        profile_model: 1,
                    },
                ],
                count_comment: 21,
                rates: [],
                count_rate: 1,
                total_rate: 4,
                arr_count_rate: [0, 0, 0, 1, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 1',
                type: 'Product type 1',
                hashtag: 'Product hashtag 3',
                name: 'Product name 3',
                new_price: 444905,
                old_price: 444905,
                discount: 1,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 39,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-13T21:25:14.131178Z',
                shop_model: 2,
                list_model: null,
            },
            {
                id: 7,
                vid_pics: [
                    {
                        id: 35,
                        vid_pic: image_loading,
                        product_model: 7,
                    },
                    {
                        id: 61,
                        vid_pic: image_loading,
                        product_model: 7,
                    },
                    {
                        id: 96,
                        vid_pic: image_loading,
                        product_model: 7,
                    },
                ],
                comments: [],
                count_comment: 0,
                rates: [],
                count_rate: 0,
                total_rate: 0,
                arr_count_rate: [0, 0, 0, 0, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 2',
                type: 'Product type 2',
                hashtag: 'Product hashtag 6',
                name: 'Product name 6',
                new_price: 120088,
                old_price: 120088,
                discount: 2,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 72,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-13T21:25:14.131178Z',
                shop_model: 2,
                list_model: null,
            },
            {
                id: 8,
                vid_pics: [
                    {
                        id: 50,
                        vid_pic: image_loading,
                        product_model: 8,
                    },
                    {
                        id: 63,
                        vid_pic: image_loading,
                        product_model: 8,
                    },
                    {
                        id: 64,
                        vid_pic: image_loading,
                        product_model: 8,
                    },
                    {
                        id: 85,
                        vid_pic: image_loading,
                        product_model: 8,
                    },
                ],
                comments: [],
                count_comment: 0,
                rates: [],
                count_rate: 1,
                total_rate: 4,
                arr_count_rate: [0, 0, 0, 1, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 1',
                type: 'Product type 1',
                hashtag: 'Product hashtag 7',
                name: 'Product name 7',
                new_price: 137269,
                old_price: 137269,
                discount: 1,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 37,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-13T21:25:14.131178Z',
                shop_model: 2,
                list_model: null,
            },
            {
                id: 16,
                vid_pics: [
                    {
                        id: 31,
                        vid_pic: image_loading,
                        product_model: 16,
                    },
                    {
                        id: 115,
                        vid_pic: image_loading,
                        product_model: 16,
                    },
                ],
                comments: [],
                count_comment: 0,
                rates: [],
                count_rate: 0,
                total_rate: 0,
                arr_count_rate: [0, 0, 0, 0, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 4',
                type: 'Product type 4',
                hashtag: 'Product hashtag 15',
                name: 'Product name 15',
                new_price: 417828,
                old_price: 417828,
                discount: 4,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 83,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-13T21:25:14.131178Z',
                shop_model: 2,
                list_model: null,
            },
            {
                id: 17,
                vid_pics: [
                    {
                        id: 23,
                        vid_pic: image_loading,
                        product_model: 17,
                    },
                    {
                        id: 65,
                        vid_pic: image_loading,
                        product_model: 17,
                    },
                    {
                        id: 88,
                        vid_pic: image_loading,
                        product_model: 17,
                    },
                ],
                comments: [
                    {
                        id: 5,
                        user: {
                            id: 2,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'My',
                            last_name: 'My',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'c c',
                        created_time: '2021-04-17T15:30:13.228780Z',
                        product_model: 17,
                        profile_model: 2,
                    },
                    {
                        id: 4,
                        user: {
                            id: 2,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'My',
                            last_name: 'My',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'v b b b\nAdsad AD\n Asd',
                        created_time: '2021-04-17T15:29:51.665862Z',
                        product_model: 17,
                        profile_model: 2,
                    },
                    {
                        id: 3,
                        user: {
                            id: 2,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'My',
                            last_name: 'My',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'a a a a',
                        created_time: '2021-04-17T14:33:18.585393Z',
                        product_model: 17,
                        profile_model: 2,
                    },
                    {
                        id: 2,
                        user: {
                            id: 2,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'My',
                            last_name: 'My',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'a c ac',
                        created_time: '2021-04-17T14:30:17.319052Z',
                        product_model: 17,
                        profile_model: 2,
                    },
                    {
                        id: 1,
                        user: {
                            id: 2,
                            picture: image_loading,
                            cover_picture: image_loading,
                            first_name: 'My',
                            last_name: 'My',
                            nick_name: 'nkox my',
                            birth: '2021-03-28',
                            permission_birth: 0,
                            permission_friends: 0,
                            hobby: 's',
                            story: 's',
                            email: 'abcxyz@gmail.com',
                            permission_email: 0,
                            phone: '0123456789',
                            permission_phone: 0,
                            address: 'Ha Noi',
                            permission_address: 0,
                            work: 'Dev',
                            university: 'HUBT',
                            high_school: 'Hoa Lu',
                            is_online: false,
                        },
                        vid_pics: [],
                        count_vid_pic: 0,
                        text: 'a',
                        created_time: '2021-04-17T14:28:46.266872Z',
                        product_model: 17,
                        profile_model: 2,
                    },
                ],
                count_comment: 5,
                rates: [],
                count_rate: 1,
                total_rate: 4,
                arr_count_rate: [0, 0, 0, 1, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 5',
                type: 'Product type 5',
                hashtag: 'Product hashtag 16',
                name: 'Product name 16',
                new_price: 412640,
                old_price: 412640,
                discount: 5,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 22,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-23T02:27:04.690676Z',
                shop_model: 2,
                list_model: null,
            },
            {
                id: 27,
                vid_pics: [
                    {
                        id: 18,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 26,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 39,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 66,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 73,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 78,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                    {
                        id: 95,
                        vid_pic: image_loading,
                        product_model: 27,
                    },
                ],
                comments: [],
                count_comment: 0,
                rates: [],
                count_rate: 0,
                total_rate: 0,
                arr_count_rate: [0, 0, 0, 0, 0],
                user_rate: 0,
                total_add_cart: 0,
                shop: {
                    id: 2,
                    picture: '/media/Bana-Hills-Da-Nang.jpg',
                    name: 'Shop 2',
                    address: 'Product address 1',
                    info: 'Shop info 1',
                },
                brand: 'Product brand 4',
                type: 'Product type 4',
                hashtag: 'Product hashtag 26',
                name: 'Product name 26',
                new_price: 189162,
                old_price: 189162,
                discount: 4,
                description:
                    'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                total: 92,
                sold: 0,
                created_time: '2021-04-13T21:25:14.131178Z',
                updated_time: '2021-04-13T21:25:14.131178Z',
                shop_model: 2,
                list_model: null,
            },
        ],
        name: 'Shop 2',
        picture: image_loading,
        banner: image_loading,
        address: 'Product address 1',
        info: 'Shop info 1\nSentence 2\nSentence 3\nSentence 4\nSentence 5',
        created_time: '2021-04-13T21:25:13.739874Z',
        owner_info: owner_info,
        profile_model: 2,
    },
];

//
export const default_arr_product_r = {
    id: 2,
    vid_pics: [
        {
            id: 43,
            vid_pic: image_loading,
            product_model: 2,
        },
        {
            id: 44,
            vid_pic: image_loading,
            product_model: 2,
        },
    ],
    total_add_cart: 0,
    shop_obj: {
        id: 3,
        picture: image_loading,
        name: 'Shop Name 3',
        address: 'Shop address 2',
        info: 'Shop info 2',
        owner_info: owner_info,
    },
    brand: 'Product brand 5',
    type: 'Product type 5',
    hashtag: 'Product hashtag 1',
    name: 'Product name 7',
    new_price: 460696,
    old_price: 460696,
    discount: 5,
    description:
        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
    quantity: 62,
    sold: 0,
    created_time: '2021-04-13T21:25:14.131178Z',
    updated_time: '2021-04-23T02:27:05.287671Z',
};

//
export const default_arr_product = [
    {
        id: 2,
        vid_pics: [
            {
                id: 43,
                vid_pic: image_loading,
                product_model: 2,
            },
            {
                id: 44,
                vid_pic: image_loading,
                product_model: 2,
            },
        ],
        comments: [],
        count_comment: 0,
        rates: [],
        count_rate: 1,
        total_rate: 4,
        arr_count_rate: [0, 0, 0, 1, 0],
        user_rate: 0,
        total_add_cart: 0,
        shop_obj: {
            id: 3,
            picture: image_loading,
            name: 'Product name 2',
            address: 'Product address 2',
            info: 'Product info 2',
            owner_info: owner_info,
        },
        brand: 'Product brand 5',
        type: 'Product type 5',
        hashtag: 'Product hashtag 1',
        name: 'Product name 7',
        new_price: 460696,
        old_price: 460696,
        discount: 5,
        description:
            'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
        total: 62,
        sold: 0,
        created_time: '2021-04-13T21:25:14.131178Z',
        updated_time: '2021-04-23T02:27:05.287671Z',
        shop_model: 3,
        list_model: null,
    },
];

//
export const default_arr_hot_image = [
    {
        vid_pic: image_loading,
    },
    {
        vid_pic: my_image,
    },
    {
        vid_pic: image_loading,
    },
    {
        vid_pic: naruto_x_hinata,
    },
    {
        vid_pic: image_loading,
    },
    {
        vid_pic: my_image,
    },
    {
        vid_pic: image_loading,
    },
    {
        vid_pic: naruto_x_hinata,
    },
];

//
export const default_arr_cmt = [
    {
        id: 5,
        user: {
            id: 2,
            picture: image_loading,
            cover_picture: image_loading,
            first_name: 'My',
            last_name: 'My',
            nick_name: 'nkox my',
            birth: '2021-03-28',
            permission_birth: 0,
            permission_friends: 0,
            hobby: 's',
            story: 's',
            email: 'abcxyz@gmail.com',
            permission_email: 0,
            phone: '0123456789',
            permission_phone: 0,
            address: 'Ha Noi',
            permission_address: 0,
            work: 'Dev',
            university: 'HUBT',
            high_school: 'Hoa Lu',
            is_online: false,
        },
        vid_pics: [],
        count_vid_pic: 0,
        content_obj: {
            content: 'Hello',
            has_more_content: true,
        },
        created_time: '2021-04-17T15:30:13.228780Z',
        product_model: 17,
        profile_model: 2,
    },
];

//
export const default_arr_rate = {
    rate_arr: [],
    rate_count: 1,
    rate_total: 4,
    rate_num_arr: [0, 0, 0, 1, 0],
    user_rate: 0,
};

//
export const default_rate_content = {
    content: 'This is content of rate',
};

//
export const DefaultFashionCartBuy = [
    {
        // buy follow shop
        id: 20,
        products: [
            // product buy of shop
            {
                id: 26,
                product: {
                    id: 5,
                    vid_pics: [
                        {
                            id: 15,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                        {
                            id: 106,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 0,
                    total_rate: null,
                    arr_count_rate: [0, 0, 0, 0, 0],
                    user_rate: 0,
                    total_add_cart: 1,
                    shop: {
                        id: 1,
                        picture: '',
                        name: 'Product name 5',
                        address: 'Product address 5',
                        info: 'Product info 5',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 4',
                    name: 'Product name 4',
                    new_price: 397355,
                    old_price: 397355,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 91,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-13T21:25:14.131178Z',
                    shop_model: 6,
                    list_model: null,
                },
                quantity: 2,
                checked: true,
                created_time: '2021-04-21T09:20:46.510170Z',
                updated_time: '2021-04-21T09:20:46.510170Z',
                cart_model: 20,
                product_model: 5,
            },
        ],
        count_product: 1,
        checked_products: [
            {
                id: 26,
                product: {
                    id: 5,
                    vid_pics: [
                        {
                            id: 15,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                        {
                            id: 106,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 0,
                    total_rate: null,
                    arr_count_rate: [0, 0, 0, 0, 0],
                    user_rate: 0,
                    total_add_cart: 1,
                    shop: {
                        id: 1,
                        picture: '',
                        name: 'Product name 5',
                        address: 'Product address 5',
                        info: 'Product info 5',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 4',
                    name: 'Product name 4',
                    new_price: 397355,
                    old_price: 397355,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 91,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-13T21:25:14.131178Z',
                    shop_model: 6,
                    list_model: null,
                },
                quantity: 1,
                checked: true,
                created_time: '2021-04-21T09:20:46.510170Z',
                updated_time: '2021-04-21T09:20:46.510170Z',
                cart_model: 20,
                product_model: 5,
            },
            {
                id: 27,
                product: {
                    id: 6,
                    vid_pics: [
                        {
                            id: 15,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                        {
                            id: 106,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 0,
                    total_rate: null,
                    arr_count_rate: [0, 0, 0, 0, 0],
                    user_rate: 0,
                    total_add_cart: 1,
                    shop: {
                        id: 1,
                        picture: '',
                        name: 'Product name 5',
                        address: 'Product address 5',
                        info: 'Product info 5',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 4',
                    name: 'Product name 4',
                    new_price: 397355,
                    old_price: 397355,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 91,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-13T21:25:14.131178Z',
                    shop_model: 6,
                    list_model: null,
                },
                quantity: 1,
                checked: true,
                created_time: '2021-04-21T09:20:46.510170Z',
                updated_time: '2021-04-21T09:20:46.510170Z',
                cart_model: 20,
                product_model: 5,
            },
        ],
        count_checked_product: 2,
        shop: {
            id: 1,
            picture: image_loading,
            name: 'Shop 6',
            address: 'Product address 5',
            info: 'Product info 5',
        },
        shop_model: 6,
        profile_model: 1,
    },
    {
        // buy follow shop
        id: 20,
        products: [
            // product buy of shop
            {
                id: 28,
                product: {
                    id: 7,
                    vid_pics: [
                        {
                            id: 15,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                        {
                            id: 106,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 0,
                    total_rate: null,
                    arr_count_rate: [0, 0, 0, 0, 0],
                    user_rate: 0,
                    total_add_cart: 1,
                    shop: {
                        id: 1,
                        picture: '',
                        name: 'Product name 5',
                        address: 'Product address 5',
                        info: 'Product info 5',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 4',
                    name: 'Product name 4',
                    new_price: 397355,
                    old_price: 397355,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 91,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-13T21:25:14.131178Z',
                    shop_model: 6,
                    list_model: null,
                },
                quantity: 3,
                checked: true,
                created_time: '2021-04-21T09:20:46.510170Z',
                updated_time: '2021-04-21T09:20:46.510170Z',
                cart_model: 20,
                product_model: 5,
            },
        ],
        count_product: 1,
        checked_products: [
            {
                id: 28,
                product: {
                    id: 7,
                    vid_pics: [
                        {
                            id: 15,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                        {
                            id: 106,
                            vid_pic:
                                image_loading,
                            product_model: 5,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 0,
                    total_rate: null,
                    arr_count_rate: [0, 0, 0, 0, 0],
                    user_rate: 0,
                    total_add_cart: 1,
                    shop: {
                        id: 1,
                        picture: '',
                        name: 'Product name 5',
                        address: 'Product address 5',
                        info: 'Product info 5',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 4',
                    name: 'Product name 4',
                    new_price: 397355,
                    old_price: 397355,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 91,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-13T21:25:14.131178Z',
                    shop_model: 6,
                    list_model: null,
                },
                quantity: 1,
                checked: true,
                created_time: '2021-04-21T09:20:46.510170Z',
                updated_time: '2021-04-21T09:20:46.510170Z',
                cart_model: 20,
                product_model: 5,
            },
        ],
        count_checked_product: 0,
        shop: {
            id: 1,
            picture: image_loading,
            name: 'Shop 4',
            address: 'Product address 5',
            info: 'Product info 5',
        },
        shop_model: 4,
        profile_model: 1,
    },
];

//
export const default_arr_transporter = [
    {
        id: 1,
        info: 'a b c d e f as sd\nasd asd asd asd a',
        name: 'Ninja Van',
        created_time: '2021-04-22T10:00:13Z',
        price_arr: [
            {
                title: 'Ninja 1',
                price: 18000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
            {
                title: 'Ninja 2',
                price: 20000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
            {
                title: 'Ninja 3',
                price: 25000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
        ],
    },
    {
        id: 1,
        info: 'a b c d e f as sd\nasd asd asd asd a',
        name: 'Giao hang tiet kiem',
        created_time: '2021-04-22T10:00:13Z',
        price_arr: [
            {
                title: 'tk 1',
                price: 15000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
            {
                title: 'tk 2',
                price: 19000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
            {
                title: 'tk 3',
                price: 22000,
                id: 1,
                info: 'Price 1',
                transporter_model: 1,
            },
        ],
    },
];
//
export const default_arr_payment = [
    { name: 'COD' },
    { name: 'BANK' },
    { name: 'VISA' },
    { name: 'MOMO' },
];
//
export const default_arr_voucher = [
    {
        id: 0,
        img: image_loading,
        name: 'Free 10k',
        cost: 10000,
        expires: '2 days',
        min_amount: 50000,
        total_num: 100,
        count_user: 15,
        info: 'a b c dsa as a\nas da as asd asd saa sd',
    },
    {
        id: 0,
        img: image_loading,
        name: 'Free 15k',
        cost: 15000,
        expires: '2 days',
        min_amount: 80000,
        total_num: 100,
        count_user: 15,
        info: 'a b c dsa as a\nas da as asd asd saa sd',
    },
    {
        id: 0,
        img: image_loading,
        name: 'Free 20k',
        cost: 20000,
        expires: '2 days',
        min_amount: 120000,
        total_num: 100,
        count_user: 15,
        info: 'a b c dsa as a\nas da as asd asd saa sd',
    },
    {
        id: 0,
        img: image_loading,
        name: 'Free 25k',
        cost: 25000,
        expires: '2 days',
        min_amount: 150000,
        total_num: 100,
        count_user: 15,
        info: 'a b c dsa as a\nas da as asd asd saa sd',
    },
    {
        id: 0,
        img: image_loading,
        name: 'Free 50k',
        cost: 50000,
        expires: '2 days',
        min_amount: 350000,
        total_num: 100,
        count_user: 15,
        info: 'a b c dsa as a\nas da as asd asd saa sd',
    },
];

//
export const default_arr_buy = [
    {
        // buy_shop
        id: 1,
        products: [
            {
                // buy_product
                id: 1,
                product: {
                    id: 2,
                    vid_pics: [
                        {
                            id: 43,
                            vid_pic: image_loading,
                            product_model: 2,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 1',
                    name: 'Product name 1',
                    new_price: 460696,
                    old_price: 460696,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 62,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:27:05.287671Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 2,
                buy_shop_model: 1,
                product_model: 2,
            },
            {
                id: 2,
                product: {
                    id: 28,
                    vid_pics: [
                        {
                            id: 27,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 60,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 92,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 93,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 108,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 112,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 3',
                    type: 'Product type 3',
                    hashtag: 'Product hashtag 27',
                    name: 'Product name 27',
                    new_price: 31135,
                    old_price: 31135,
                    discount: 3,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 6,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:38:00.102311Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 1,
                buy_shop_model: 1,
                product_model: 28,
            },
        ],
        shop: {
            id: 3,
            picture: '',
            name: 'Shop 1',
            address: 'Product address 2',
            info: 'Product info 2',
        },
        payment: 'COD',
        status: 'BUYING',
        created_time: '2021-04-23T09:31:11.551079Z',
        updated_time: '2021-04-23T09:31:11.551079Z',
        profile_model: 1,
        shop_model: 3,
        transport_price_model: 1,
        voucher_model: 1,
    },
    {
        // buy_shop
        id: 1,
        products: [
            {
                // buy_product
                id: 1,
                product: {
                    id: 2,
                    vid_pics: [
                        {
                            id: 43,
                            vid_pic: image_loading,
                            product_model: 2,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 1',
                    name: 'Product name 3',
                    new_price: 460696,
                    old_price: 460696,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 62,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:27:05.287671Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 2,
                buy_shop_model: 1,
                product_model: 2,
            },
            {
                id: 2,
                product: {
                    id: 28,
                    vid_pics: [
                        {
                            id: 27,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 60,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 92,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 93,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 108,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 112,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Shop 3243',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 3',
                    type: 'Product type 3',
                    hashtag: 'Product hashtag 27',
                    name: 'Product name 4',
                    new_price: 31135,
                    old_price: 31135,
                    discount: 3,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 6,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:38:00.102311Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 1,
                buy_shop_model: 1,
                product_model: 28,
            },
        ],
        shop: {
            id: 3,
            picture: '',
            name: 'Shop 3',
            address: 'Product address 2',
            info: 'Product info 2',
        },
        payment: 'COD',
        status: 'BUYING',
        created_time: '2021-04-23T09:31:11.551079Z',
        updated_time: '2021-04-23T09:31:11.551079Z',
        profile_model: 1,
        shop_model: 3,
        transport_price_model: 1,
        voucher_model: 1,
    },
    {
        // buy_shop
        id: 1,
        products: [
            {
                // buy_product
                id: 1,
                product: {
                    id: 2,
                    vid_pics: [
                        {
                            id: 43,
                            vid_pic: image_loading,
                            product_model: 2,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 1',
                    name: 'Product name 5',
                    new_price: 460696,
                    old_price: 460696,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 62,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:27:05.287671Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 2,
                buy_shop_model: 1,
                product_model: 2,
            },
        ],
        shop: {
            id: 3,
            picture: '',
            name: 'Shop 1233',
            address: 'Product address 2',
            info: 'Product info 2',
        },
        payment: 'COD',
        status: 'DELIVERY',
        created_time: '2021-04-23T09:31:11.551079Z',
        updated_time: '2021-04-23T09:31:11.551079Z',
        profile_model: 1,
        shop_model: 3,
        transport_price_model: 1,
        voucher_model: 1,
    },
    {
        // buy_shop
        id: 1,
        products: [
            {
                // buy_product
                id: 1,
                product: {
                    id: 2,
                    vid_pics: [
                        {
                            id: 43,
                            vid_pic: image_loading,
                            product_model: 2,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 5',
                    type: 'Product type 5',
                    hashtag: 'Product hashtag 1',
                    name: 'Product name 7',
                    new_price: 460696,
                    old_price: 460696,
                    discount: 5,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 62,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:27:05.287671Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 2,
                buy_shop_model: 1,
                product_model: 2,
            },
            {
                id: 2,
                product: {
                    id: 28,
                    vid_pics: [
                        {
                            id: 27,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 60,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 92,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 93,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 108,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                        {
                            id: 112,
                            vid_pic: image_loading,
                            product_model: 28,
                        },
                    ],
                    comments: [],
                    count_comment: 0,
                    rates: [],
                    count_rate: 1,
                    total_rate: 4,
                    arr_count_rate: [0, 0, 0, 1, 0],
                    user_rate: 0,
                    total_add_cart: 0,
                    shop: {
                        id: 3,
                        picture: '',
                        name: 'Product name 2',
                        address: 'Product address 2',
                        info: 'Product info 2',
                    },
                    brand: 'Product brand 3',
                    type: 'Product type 3',
                    hashtag: 'Product hashtag 8',
                    name: 'Product name 27',
                    new_price: 81135,
                    old_price: 91135,
                    discount: 3,
                    description:
                        'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
                    total: 6,
                    sold: 0,
                    created_time: '2021-04-13T21:25:14.131178Z',
                    updated_time: '2021-04-23T02:38:00.102311Z',
                    shop_model: 3,
                    list_model: null,
                },
                quantity: 1,
                buy_shop_model: 1,
                product_model: 28,
            },
        ],
        shop: {
            id: 3,
            picture: '',
            name: 'Shop 112',
            address: 'Product address 2',
            info: 'Product info 2',
        },
        payment: 'BANKING',
        status: 'BOUGHT',
        created_time: '2021-04-23T09:31:11.551079Z',
        updated_time: '2021-04-23T09:31:11.551079Z',
        profile_model: 1,
        shop_model: 3,
        transport_price_model: 1,
        voucher_model: 1,
    },
];

//
export const default_arr_cancel = [
    {
        // buy_product
        id: 1,
        product: {
            id: 2,
            vid_pics: [
                {
                    id: 43,
                    vid_pic: image_loading,
                    product_model: 2,
                },
            ],
            comments: [],
            count_comment: 0,
            rates: [],
            count_rate: 1,
            total_rate: 4,
            arr_count_rate: [0, 0, 0, 1, 0],
            user_rate: 0,
            total_add_cart: 0,
            shop: {
                id: 3,
                picture: '',
                name: 'Product name 2',
                address: 'Product address 2',
                info: 'Product info 2',
            },
            brand: 'Product brand 5',
            type: 'Product type 5',
            hashtag: 'Product hashtag 1',
            name: 'Product name 7',
            new_price: 460696,
            old_price: 460696,
            discount: 5,
            description:
                'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
            total: 62,
            sold: 0,
            created_time: '2021-04-13T21:25:14.131178Z',
            updated_time: '2021-04-23T02:27:05.287671Z',
            shop_model: 3,
            list_model: null,
        },
        quantity: 2,
        buy_shop_model: 1,
        product_model: 2,
    },
    {
        id: 2,
        product: {
            id: 28,
            vid_pics: [
                {
                    id: 27,
                    vid_pic: image_loading,
                    product_model: 28,
                },
                {
                    id: 60,
                    vid_pic: image_loading,
                    product_model: 28,
                },
                {
                    id: 92,
                    vid_pic: image_loading,
                    product_model: 28,
                },
                {
                    id: 93,
                    vid_pic: image_loading,
                    product_model: 28,
                },
                {
                    id: 108,
                    vid_pic: image_loading,
                    product_model: 28,
                },
                {
                    id: 112,
                    vid_pic: image_loading,
                    product_model: 28,
                },
            ],
            comments: [],
            count_comment: 0,
            rates: [],
            count_rate: 1,
            total_rate: 4,
            arr_count_rate: [0, 0, 0, 1, 0],
            user_rate: 0,
            total_add_cart: 0,
            shop: {
                id: 3,
                picture: '',
                name: 'Product name 2',
                address: 'Product address 2',
                info: 'Product info 2',
            },
            brand: 'Product brand 3',
            type: 'Product type 3',
            hashtag: 'Product hashtag 8',
            name: 'Product name 27',
            new_price: 81135,
            old_price: 91135,
            discount: 3,
            description:
                'Product description a dasd asd\nasd asd asd asd\nas ad ad asda sd\n asdada d',
            total: 6,
            sold: 0,
            created_time: '2021-04-13T21:25:14.131178Z',
            updated_time: '2021-04-23T02:38:00.102311Z',
            shop_model: 3,
            list_model: null,
        },
        quantity: 1,
        buy_shop_model: 1,
        product_model: 28,
    },
];
