
//
export const reduxConstFashion = {
    GET_CART: 'GET_CART',
    ADD_CART_ALREADY_PRODUCT: 'ADD_CART_ALREADY_PRODUCT',
    ADD_CART_ALREADY_SHOP: 'ADD_CART_ALREADY_SHOP',
    ADD_CART_NEW_SHOP: 'ADD_CART_NEW_SHOP',
    DELETE_PRODUCTS_CART: 'DELETE_PRODUCTS_CART',
}
