const item_obj = {
    itemid: 5764141997,
    shopid: 304092705,
    userid: 0,
    price_max_before_discount: 38000000000,
    has_lowest_price_guarantee: false,
    price_before_discount: 14800000000,
    price_min_before_discount: 14800000000,
    exclusive_price_info: null,
    hidden_price_display: null,
    price_min: 14800000000,
    price_max: 31800000000,
    price: 14800000000,
    stock: 600,
    discount: '28%',
    historical_sold: 656,
    sold: 109,
    show_discount: 28,
    raw_discount: 28,
    min_purchase_limit: 0,
    overall_purchase_limit: {
        order_max_purchase_limit: 0,
        overall_purchase_limit: null,
        item_overall_quota: null,
        start_date: null,
        end_date: null,
    },
    pack_size: null,
    is_live_streaming_price: null,
    name: '[Auth-Date mới] Benzac AC 2.5%, 5% - Kem hỗ trợ giảm mụn',
    ctime: 1605863605,
    item_status: 'normal',
    status: 1,
    condition: 1,
    catid: 100630,

    attributes: [
        {
            name: 'Xuất xứ',
            value: 'Việt Nam',
            id: 100037,
            is_timestamp: false,
            brand_option: null,
            val_id: null,
        },
    ],

    description:
        'Thành phần:\nBenzoyl Peroxide 2.5%, 5%\n\nCông dụng:\nKhi thoa lên da mụn, Benzac AC sẽ có những tác dụng:\n- Điều tiết và kiểm soát dư lượng nhờn thừa trên bề mặt da\n- Hoạt chất giảm mụn trứng cá, mụn bọc hay mụn sưng, giúp cải thiện da mụn chỉ từ 5 – 7 ngày.\n- Benzac AC có tính tiêu sừng, vì thế góp phần giảm mụn đầu trắng, mụn đầu đen, đồng thời giảm sưng, đỏ, hạn chế để lại thâm, sẹo.\n\nCách dùng:\nRửa mặt sạch bằng sữa rửa mặt (chỉ dùng tẩy trang khi có trang điểm).\nThoa kem Benzac AC 2 lần/ngày (sáng và chiều), để khô tự nhiên, không rửa mặt lại.\nCó thể dùng thêm tinh chất, serum dưỡng ẩm,… sau đó 30 phút.\n\n#benzac\n#benzac_ac_5\n#benzac_5\n#benzac_ac\n#benzoyl_peroxide\n',
    is_mart: false,
    show_shopee_verified_label: true,
    size_chart: null,
    reference_item_id: '',
    brand: null,
    item_rating: {
        rating_star: 4.927350427350428,
        rating_count: [234, 0, 2, 3, 5, 224],
    },
    label_ids: [1003958],
    // attributes: null,
    liked: false,
    liked_count: 4137,
    cmt_count: 234,
    flag: 0,
    shopee_verified: true,
    is_adult: false,
    is_preferred_plus_seller: false,
    tier_variations: [
        {
            name: 'Hàm lượng',
            options: [
                '2.5% - 15g',
                '5% - 15g',
                '2.5% - 60g',
                '5% - 60g',
                '5%- 15g hộp móp',
                '2.5% -15g hộp móp',
            ],
            images: [''],
            properties: null,
            type: 0,
        },
    ],
    bundle_deal_id: 0,
    can_use_bundle_deal: false,
    add_on_deal_info: null,
    bundle_deal_info: null,
    can_use_wholesale: false,
    wholesale_tier_list: [],
    is_group_buy_item: null,
    group_buy_info: null,
    welcome_package_type: 0,
    welcome_package_info: null,
    images: [''],
    image: '',
    video_info_list: [
        {
            video_id: '',
            thumb_url: '',
            duration: 59,
            version: 1,
            formats: [],
            default_format: null,
        },
    ],
    item_type: 0,
    is_official_shop: false,
    show_official_shop_label_in_title: false,
    shop_location: 'TP. Hồ Chí Minh',
    coin_earn_label: null,
    cb_option: 0,
    is_pre_order: false,
    estimated_days: 2,
    badge_icon_type: 0,
    show_free_shipping: false,
    shipping_icon_type: 0,
    cod_flag: 0,
    show_original_guarantee: false,
    categories: [
        {
            catid: 100630,
            display_name: 'Sắc Đẹp',
            no_sub: false,
            is_default_subcat: false,
        },
        {
            catid: 100664,
            display_name: 'Chăm sóc da mặt',
            no_sub: false,
            is_default_subcat: false,
        },
        {
            catid: 100904,
            display_name: 'Sản phẩm trị mụn',
            no_sub: true,
            is_default_subcat: false,
        },
    ],
    other_stock: 288,
    item_has_post: true,
    discount_stock: 312,
    current_promotion_has_reserve_stock: false,
    current_promotion_reserved_stock: 0,
    normal_stock: 600,
    brand_id: 0,
    is_alcohol_product: false,
    show_recycling_info: false,
    coin_info: {
        spend_cash_unit: 100000,
        coin_earn_items: [],
    },
    models: [
        {
            itemid: 5764141997,
            status: 1,
            current_promotion_reserved_stock: 0,
            name: '2.5% - 15g',
            promotionid: 1265381606,
            price: 14800000000,
            price_stocks: [
                {
                    allocated_stock: 0,
                    stock_breakdown_by_location: null,
                },
                {
                    allocated_stock: null,
                    stock_breakdown_by_location: null,
                },
            ],
            current_promotion_has_reserve_stock: false,
            normal_stock: 266,
            extinfo: {
                tier_index: [0],
                group_buy_info: null,
            },
            price_before_discount: 20500000000,
            modelid: 72289738345,
            stock: 266,
            has_gimmick_tag: false,
        },
    ],
    spl_info: null,
    preview_info: null,
    is_cc_installment_payment_eligible: false,
    is_non_cc_installment_payment_eligible: false,
    flash_sale: null,
    upcoming_flash_sale: null,
    deep_discount: null,
    has_low_fulfillment_rate: false,
    is_partial_fulfilled: false,
    makeups: null,
};

const shopInfo = {
    shopid: 304092705,
    userid: 304112290,
    last_active_time: 1629378431,
    vacation: false,
    place: 'Quận Gò Vấp, TP. Hồ Chí Minh',
    account: {
        portrait: '92980a7c977cfc00cbefb21efdb47a1d',
        username: 'tretinoin_gel',
        status: 1,
    },
    is_shopee_verified: true,
    is_preferred_plus_seller: false,
    is_official_shop: false,
    shop_location: 'TP. Hồ Chí Minh',
    item_count: 94,
    rating_star: 4.943958,
    response_rate: 85,
    session_info: {
        is_show: false,
        session_id: 0,
        view_count: 0,
        session_url: '',
        preview_image: '',
    },
    name: 'Tuyet Anh Cosmeceuticals',
    ctime: 1599022641,
    response_time: 9789,
    follower_count: 12494,
    show_official_shop_label: false,
    rating_bad: 11,
    rating_good: 2857,
    rating_normal: 21,
};

const bundle_deal = {
    items: [
        {
            itemid: 5441309671,
            price_max_before_discount: 33000000000,
            item_status: 'normal',
            can_use_wholesale: false,
            brand_id: null,
            show_free_shipping: true,
            estimated_days: 2,
            is_hot_sales: null,
            is_slash_price_item: null,
            upcoming_flash_sale: null,
            slash_lowest_price: null,
            is_partial_fulfilled: null,
            condition: 1,
            show_original_guarantee: null,
            add_on_deal_info: null,
            is_non_cc_installment_payment_eligible: false,
            categories: null,
            ctime: 1594152755,
            name: 'Benzac AC ⚜️CHÍNH HÃNG⚜️ Kem ngừa mụn Benzac AC Benzoyl Peroxide - Galderma',
            show_shopee_verified_label: true,
            userid: null,
            size_chart: null,
            is_pre_order: false,
            service_by_shopee_flag: null,
            historical_sold: 3103,
            reference_item_id: '',
            recommendation_info: null,
            bundle_deal_info: {
                bundle_deal_id: 10890238,
                bundle_deal_label: 'Mua 2 & giảm ₫2.000',
            },
            bundle_deal_id: 10890238,
            has_lowest_price_guarantee: true,
            shipping_icon_type: null,
            overall_purchase_limit: {
                order_max_purchase_limit: 0,
                item_overall_quota: null,
                overall_purchase_limit: null,
                end_date: null,
                start_date: null,
            },
            images: ['fb68e17975e11ae37bedbfdd90192fbc'],
            price_before_discount: 15000000000,
            cod_flag: null,
            catid: 100630,
            is_official_shop: false,
            is_mart: false,
            coin_earn_label: null,
            hashtag_list: null,
            sold: 331,
            makeup: null,
            item_rating: {
                rating_star: 4.978508,
                rating_count: [791, 0, 0, 3, 11, 777],
                rcount_with_image: 366,
                rcount_with_context: 421,
            },
            show_official_shop_label_in_title: false,
            discount: '7%',
            reason: null,
            label_ids: [1003958],
            has_group_buy_stock: null,
            other_stock: null,
            deep_discount: null,
            attributes: [],
            pack_size: null,
            last_active_time: null,
            badge_icon_type: 0,
            liked: false,
            is_on_flash_sale: null,
            cmt_count: 791,
            is_live_streaming_price: null,
            image: 'fb68e17975e11ae37bedbfdd90192fbc',
            recommendation_algorithm: null,
            is_cc_installment_payment_eligible: false,
            shopid: 12095101,
            normal_stock: null,
            video_info_list: [
                {
                    video_id: 'b67653988e0318ebc2c3b4f69283bf56',
                    version: 2,
                    formats: [],
                    duration: 38,
                    default_format: null,
                    thumb_url: '02a31696d3bfce385c571537af27ea57',
                },
            ],
            installment_plans: null,
            view_count: 12829,
            voucher_info: null,
            current_promotion_has_reserve_stock: null,
            liked_count: 835,
            show_official_shop_label: false,
            price_min_before_discount: 15000000000,
            show_discount: 7,
            preview_info: null,
            flag: 2,
            exclusive_price_info: null,
            current_promotion_reserved_stock: null,
            wholesale_tier_list: [],
            group_buy_info: null,
            shopee_verified: true,
            item_has_post: null,
            hidden_price_display: null,
            transparent_background_image: '',
            welcome_package_info: null,
            discount_stock: null,
            coin_info: null,
            is_adult: false,
            currency: 'VND',
            raw_discount: 7,
            is_preferred_plus_seller: false,
            is_category_failed: false,
            price_min: 14000000000,
            can_use_bundle_deal: true,
            cb_option: 0,
            brand: 'No Brand',
            stock: 488,
            status: 1,
            price_max: 31500000000,
            spl_info: null,
            is_group_buy_item: null,
            description: null,
            flash_sale: null,
            models: [
                {
                    itemid: 5441309671,
                    status: 1,
                    current_promotion_reserved_stock: null,
                    name: '5% - 60g',
                    promotionid: 1275814267,
                    price: 31500000000,
                    price_stocks: null,
                    current_promotion_has_reserve_stock: null,
                    currency: 'VND',
                    normal_stock: null,
                    extinfo: {
                        seller_promotion_limit: 0,
                        has_shopee_promo: true,
                        group_buy_info: null,
                        holiday_mode_old_stock: null,
                        tier_index: [2],
                        seller_promotion_refresh_time: 1629770400,
                    },
                    has_gimmick_tag: null,
                    price_before_discount: 33000000000,
                    modelid: 50811220614,
                    sold: 306,
                    stock: 12,
                },
            ],
            has_low_fulfillment_rate: null,
            price: 14000000000,
            shop_location: 'Hà Nội',
            tier_variations: [
                {
                    images: ['f20fa375594daa35a3bf4c20b8155f2f'],
                    properties: [],
                    type: 0,
                    name: 'benzac ac',
                    options: ['2.5% - 15g', '5% - 15g', '5% - 60g'],
                },
            ],
            min_purchase_limit: 0,
            can_use_cod: null,
            makeups: null,
            welcome_package_type: 0,
            show_official_shop_label_in_normal_position: null,
            is_alcohol_product: null,
            item_type: 0,
            spl_installment_tenure: null,
            show_recycling_info: null,
        },
    ],
    nextOffset: 9,
    hasMore: false,
    limit: 20,
    total: 9,
    bundle_deal_id: 10890238,
    bundle_deal_label: 'Mua 2 & giảm ₫2.000',
    bundleDealId: 10890238,
    bundleDealLabel: 'Mua 2 & giảm ₫2.000',
    start_time: 1629347400,
    end_time: 1637386200,
    flag: 2,
    status: 1,
    shopid: 12095101,
    loading: false,
};

const gift = {
    id: 1858320391,
    mainItemCards: [
        {
            id: '2470767669',
            image: 'https://cf.shopee.vn/file/869eb5e6e5291b85c2c6625922c5468b_tn',
            name: 'Quần bò baggy rách vuông',
        },
    ],
    giftItemCards: [
        {
            id: '887675887593368111639',
            image: 'https://cf.shopee.vn/file/6e5395493cef96807538cbba2c0ce3d2_tn',
            name: '2 khẩu trang đúc su không chọn màu',
        },
    ],
    mainCounts: 27,
    giftCounts: 1,
    maxMainItemsDisplayed: 2,
    maxGiftItemsDisplayed: 4,
    minSpend: 100000000,
    giftCount: 1,
};
